# Example-04: Quadrupole element factory

In [1]:
# In this example quadrupole factory is illustrated

In [2]:
import jax
from jax import jit
from jax import jacrev

from elementary.util import ptc
from elementary.util import beta
from elementary.quadrupole import quadrupole_factory

jax.numpy.set_printoptions(linewidth=256, precision=12)

In [3]:
# Set data type

jax.config.update("jax_enable_x64", True)

In [4]:
# Set device

device, *_ = jax.devices('cpu')
jax.config.update('jax_default_device', device)

In [5]:
# Set initial condition

(q_x, q_y, q_s) = qs = jax.numpy.array([-0.01, 0.005, 0.001])
(p_x, p_y, p_s) = ps = jax.numpy.array([0.001, 0.001, -0.0001])
x = jax.numpy.hstack([qs, ps])

In [6]:
# Define generic quadrupole element

gamma = 10**6
length = 1.0

element = jit(quadrupole_factory(beta=beta(gamma), gamma=gamma, order=2**1, iterations=100, settings=dict(ns=2**1)))

In [7]:
# Compare with PTC

length = jax.numpy.float64(1.0)
kn = jax.numpy.float64(-2.0)
ks = jax.numpy.float64(+1.5)

print(res := element(x, length, kn, ks))
print(ref := ptc(x, 'quadrupole', {'l': float(length), 'k1': float(kn), 'k1s': float(ks)}, gamma=gamma))
print(jax.numpy.allclose(res, ref))

[-0.017335308273 -0.005444917173  0.000881618072 -0.020606852812 -0.020050030435 -0.0001        ]
[-0.017335308273 -0.005444917173  0.000881618072 -0.020606852812 -0.020050030435 -0.0001        ]
True


In [8]:
# Differentiability

print(jacrev(element)(x, length, kn, ks))
print()

print(jacrev(element, 1)(x, length, kn, ks))
print()

[[ 2.279575304163e+00  7.632479527223e-01  0.000000000000e+00  1.388655261285e+00  2.520951472221e-01  9.491020612615e-03]
 [ 7.636609189649e-01  2.438324624109e-01  0.000000000000e+00  2.522344406143e-01  7.165998019815e-01  9.548550668937e-03]
 [ 2.540181616181e-02 -1.691651234625e-03  1.000000000000e+00  1.634206701237e-02  9.283951302092e-03  2.532776862723e-04]
 [ 3.154287926409e+00  1.578288131758e+00  0.000000000000e+00  2.279171804418e+00  7.632559539488e-01  9.596394525419e-03]
 [ 1.578258960749e+00 -1.054777136233e+00  0.000000000000e+00  7.631214547666e-01  2.439057832275e-01 -2.972553251711e-03]
 [-1.620874931345e-20 -2.873327146827e-21  0.000000000000e+00 -7.911773602881e-21 -1.482149988177e-21  1.000000000000e+00]]

[-2.061743883357e-02 -2.006033040858e-02 -4.136622618369e-04 -4.283799230736e-02 -1.511312806386e-02  2.990889984494e-22]

