# Example-08: Dipole element factory (body)

In [1]:
# In this example dipole factory is illustrated

In [2]:
import jax
from jax import jit
from jax import jacrev

from elementary.util import ptc
from elementary.util import beta
from elementary.dipole import dipole_factory

jax.numpy.set_printoptions(linewidth=256, precision=12)

In [3]:
# Set data type

jax.config.update("jax_enable_x64", True)

In [4]:
# Set device

device, *_ = jax.devices('cpu')
jax.config.update('jax_default_device', device)

In [5]:
# Set initial condition

(q_x, q_y, q_s) = qs = jax.numpy.array([-0.01, 0.005, 0.001])
(p_x, p_y, p_s) = ps = jax.numpy.array([0.001, 0.001, -0.0001])
x = jax.numpy.hstack([qs, ps])

In [6]:
# Define generic quadrupole element

gamma = 10**6
element = jit(dipole_factory(beta=beta(gamma), gamma=gamma, order=2**1, iterations=100, settings=dict(ns=2**1)))

In [7]:
# Compare with PTC

length = jax.numpy.float64(2.0)
angle = jax.numpy.float64(0.05)

print(res := element(x, length, angle))
print(ref := ptc(x, 'sbend', {'l': float(length), 'angle': float(angle), 'kill_ent_fringe': 'true', 'kill_exi_fringe': 'true'}, gamma=gamma))
print(jax.numpy.allclose(res, ref))

[-0.007993633465  0.006999752089  0.001447886312  0.001006197152  0.001          -0.0001        ]
[-0.007993633465  0.006999752089  0.001447886312  0.001006197152  0.001          -0.0001        ]
True


In [8]:
# Differentiability

print(jacrev(element)(x, length, angle))
print()

print(jacrev(element, 1)(x, length, angle))
print()

[[ 9.988005543727e-01  0.000000000000e+00  0.000000000000e+00  1.998921181261e+00 -4.798292007475e-05  4.797812178277e-02]
 [ 4.998421799247e-05  1.000000000000e+00  0.000000000000e+00  5.199395592224e-05  1.999754088219e+00 -1.999122783077e-03]
 [-4.997921957070e-02  0.000000000000e+00  1.000000000000e+00 -5.198875652668e-02 -1.999122783077e-03 -8.292180969377e-04]
 [-1.249479231767e-03  0.000000000000e+00  0.000000000000e+00  9.987002761773e-01 -4.998421768169e-05  4.997921925994e-02]
 [-1.549980530634e-25  0.000000000000e+00  0.000000000000e+00  6.017762306606e-25  1.000000000000e+00  6.199014981798e-24]
 [-8.988083938862e-29  0.000000000000e+00  0.000000000000e+00 -7.109608908304e-29  2.639602544579e-29  1.000000000000e+00]]

[ 9.971860391506e-04  1.000125965538e-03 -2.595294164285e-05 -6.247396158831e-06 -3.836637364804e-28 -1.379193256298e-30]

